import type {
  Job,
  Application,
  Interview,
  DashboardStats,
  StatusSummary,
} from "./types"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "UX/UI Designer",
    type: "full_time",
    description:
      "Design intuitive and engaging user experiences for our products, working closely with developers and product teams.",
    requirements: [
      "3+ years of experience in UX/UI design",
      "Proficiency in Figma and Adobe Creative Suite",
      "Strong portfolio demonstrating design thinking",
      "Experience with design systems",
      "Excellent communication skills",
    ],
    headcount: 2,
    salary_min: 70000,
    salary_max: 95000,
    urgent: true,
    status: "open",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-01-15T10:00:00Z",
    created_by: "admin001",
  },
  {
    id: "2",
    title: "Frontend Developer",
    type: "full_time",
    description:
      "Build responsive and performant web applications using modern frameworks and best practices.",
    requirements: [
      "4+ years of experience with React or Vue",
      "Strong TypeScript skills",
      "Experience with state management libraries",
      "Knowledge of CSS-in-JS solutions",
      "Familiarity with testing frameworks",
    ],
    headcount: 3,
    salary_min: 80000,
    salary_max: 120000,
    urgent: false,
    status: "open",
    created_at: "2024-01-10T09:00:00Z",
    updated_at: "2024-01-10T09:00:00Z",
    created_by: "admin001",
  },
  {
    id: "3",
    title: "Product Manager",
    type: "full_time",
    description:
      "Lead product strategy and roadmap, collaborating with cross-functional teams to deliver exceptional products.",
    requirements: [
      "5+ years of product management experience",
      "Experience with agile methodologies",
      "Strong analytical and data-driven mindset",
      "Excellent stakeholder management skills",
      "Technical background preferred",
    ],
    headcount: 1,
    salary_min: 90000,
    salary_max: 130000,
    urgent: false,
    status: "open",
    created_at: "2024-01-08T14:00:00Z",
    updated_at: "2024-01-08T14:00:00Z",
    created_by: "admin001",
  },
  {
    id: "4",
    title: "Marketing Intern",
    type: "internship",
    description:
      "Support marketing campaigns and learn digital marketing strategies in a fast-paced startup environment.",
    requirements: [
      "Currently pursuing Marketing or related degree",
      "Strong written communication skills",
      "Familiarity with social media platforms",
      "Creative mindset",
      "Eager to learn",
    ],
    headcount: 2,
    salary_min: 20000,
    salary_max: 30000,
    urgent: false,
    status: "open",
    created_at: "2024-01-05T11:00:00Z",
    updated_at: "2024-01-05T11:00:00Z",
    created_by: "admin001",
  },
  {
    id: "5",
    title: "DevOps Engineer",
    type: "contract",
    description:
      "Implement and maintain CI/CD pipelines, infrastructure automation, and cloud services.",
    requirements: [
      "3+ years of DevOps experience",
      "Experience with AWS or GCP",
      "Proficiency in Docker and Kubernetes",
      "Strong scripting skills (Python, Bash)",
      "Knowledge of infrastructure as code",
    ],
    headcount: 1,
    salary_min: 85000,
    salary_max: 110000,
    urgent: true,
    status: "open",
    created_at: "2024-01-03T08:00:00Z",
    updated_at: "2024-01-03T08:00:00Z",
    created_by: "admin001",
  },
]

export const mockArchivedJobs: Job[] = [
  {
    id: "6",
    title: "Data Analyst",
    type: "full_time",
    description: "Analyze data and provide insights to drive business decisions.",
    requirements: [
      "2+ years of data analysis experience",
      "Proficiency in SQL and Python",
      "Experience with visualization tools",
    ],
    headcount: 1,
    salary_min: 60000,
    salary_max: 80000,
    urgent: false,
    status: "closed",
    created_at: "2023-12-01T10:00:00Z",
    updated_at: "2024-01-01T10:00:00Z",
    created_by: "admin001",
  },
]

export const mockApplications: Application[] = [
  {
    id: "1",
    job_id: "1",
    job_title: "UX/UI Designer",
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@email.com",
    phone: "+1 234 567 8901",
    resume_url: "https://example.com/resume1.pdf",
    portfolio_url: "https://johndoe.design",
    status: "screening",
    created_at: "2024-01-16T09:00:00Z",
    updated_at: "2024-01-17T10:00:00Z",
    token: "abc123",
  },
  {
    id: "2",
    job_id: "1",
    job_title: "UX/UI Designer",
    first_name: "Jane",
    last_name: "Smith",
    email: "jane.smith@email.com",
    phone: "+1 234 567 8902",
    resume_url: "https://example.com/resume2.pdf",
    portfolio_url: "https://janesmith.design",
    status: "interview",
    interview_date: "2024-01-25T14:00:00Z",
    created_at: "2024-01-14T11:00:00Z",
    updated_at: "2024-01-18T15:00:00Z",
    token: "def456",
  },
  {
    id: "3",
    job_id: "2",
    job_title: "Frontend Developer",
    first_name: "Mike",
    last_name: "Johnson",
    email: "mike.johnson@email.com",
    phone: "+1 234 567 8903",
    resume_url: "https://example.com/resume3.pdf",
    status: "applied",
    created_at: "2024-01-17T08:00:00Z",
    updated_at: "2024-01-17T08:00:00Z",
    token: "ghi789",
  },
  {
    id: "4",
    job_id: "2",
    job_title: "Frontend Developer",
    first_name: "Sarah",
    last_name: "Williams",
    email: "sarah.williams@email.com",
    phone: "+1 234 567 8904",
    resume_url: "https://example.com/resume4.pdf",
    portfolio_url: "https://sarahwilliams.dev",
    status: "offer",
    created_at: "2024-01-10T10:00:00Z",
    updated_at: "2024-01-20T09:00:00Z",
    token: "jkl012",
  },
  {
    id: "5",
    job_id: "3",
    job_title: "Product Manager",
    first_name: "Tom",
    last_name: "Brown",
    email: "tom.brown@email.com",
    phone: "+1 234 567 8905",
    resume_url: "https://example.com/resume5.pdf",
    status: "rejected",
    created_at: "2024-01-12T14:00:00Z",
    updated_at: "2024-01-15T11:00:00Z",
    token: "mno345",
  },
  {
    id: "6",
    job_id: "1",
    job_title: "UX/UI Designer",
    first_name: "Emily",
    last_name: "Davis",
    email: "emily.davis@email.com",
    phone: "+1 234 567 8906",
    resume_url: "https://example.com/resume6.pdf",
    portfolio_url: "https://emilydavis.design",
    status: "applied",
    created_at: "2024-01-18T16:00:00Z",
    updated_at: "2024-01-18T16:00:00Z",
    token: "pqr678",
  },
  {
    id: "7",
    job_id: "5",
    job_title: "DevOps Engineer",
    first_name: "Alex",
    last_name: "Martinez",
    email: "alex.martinez@email.com",
    phone: "+1 234 567 8907",
    resume_url: "https://example.com/resume7.pdf",
    status: "screening",
    created_at: "2024-01-19T09:00:00Z",
    updated_at: "2024-01-20T10:00:00Z",
    token: "stu901",
  },
  {
    id: "8",
    job_id: "4",
    job_title: "Marketing Intern",
    first_name: "Lisa",
    last_name: "Anderson",
    email: "lisa.anderson@email.com",
    phone: "+1 234 567 8908",
    resume_url: "https://example.com/resume8.pdf",
    status: "interview",
    interview_date: "2024-01-26T10:00:00Z",
    created_at: "2024-01-15T13:00:00Z",
    updated_at: "2024-01-21T14:00:00Z",
    token: "vwx234",
  },
  {
    id: "9",
    job_id: "2",
    job_title: "Frontend Developer",
    first_name: "Chris",
    last_name: "Taylor",
    email: "chris.taylor@email.com",
    phone: "+1 234 567 8909",
    resume_url: "https://example.com/resume9.pdf",
    status: "applied",
    created_at: "2024-01-20T11:00:00Z",
    updated_at: "2024-01-20T11:00:00Z",
    token: "yza567",
  },
  {
    id: "10",
    job_id: "1",
    job_title: "UX/UI Designer",
    first_name: "David",
    last_name: "Wilson",
    email: "david.wilson@email.com",
    phone: "+1 234 567 8910",
    resume_url: "https://example.com/resume10.pdf",
    portfolio_url: "https://davidwilson.design",
    status: "screening",
    created_at: "2024-01-19T15:00:00Z",
    updated_at: "2024-01-21T09:00:00Z",
    token: "bcd890",
  },
  {
    id: "11",
    job_id: "3",
    job_title: "Product Manager",
    first_name: "Rachel",
    last_name: "Garcia",
    email: "rachel.garcia@email.com",
    phone: "+1 234 567 8911",
    resume_url: "https://example.com/resume11.pdf",
    status: "interview",
    interview_date: "2024-01-27T15:00:00Z",
    created_at: "2024-01-13T10:00:00Z",
    updated_at: "2024-01-22T11:00:00Z",
    token: "efg123",
  },
  {
    id: "12",
    job_id: "5",
    job_title: "DevOps Engineer",
    first_name: "Kevin",
    last_name: "Lee",
    email: "kevin.lee@email.com",
    phone: "+1 234 567 8912",
    resume_url: "https://example.com/resume12.pdf",
    status: "applied",
    created_at: "2024-01-21T08:00:00Z",
    updated_at: "2024-01-21T08:00:00Z",
    token: "hij456",
  },
]

export const mockInterviews: Interview[] = [
  {
    id: "1",
    application_id: "2",
    applicant_name: "Jane Smith",
    job_title: "UX/UI Designer",
    date: "2024-01-25",
    time: "14:00",
  },
  {
    id: "2",
    application_id: "8",
    applicant_name: "Lisa Anderson",
    job_title: "Marketing Intern",
    date: "2024-01-26",
    time: "10:00",
  },
]

export const mockDashboardStats: DashboardStats = {
  total_jobs: 5,
  total_urgent_jobs: 2,
  total_applications: 12,
}

export const mockStatusSummary: StatusSummary = {
  applied: 4,
  screening: 3,
  interview: 3,
  offer: 1,
  rejected: 1,
}
